package tests;

import java.sql.Time;
import java.util.Iterator;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import java.util.logging.Logger;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.sikuli.script.FindFailed;
import org.sikuli.script.Pattern;
import org.sikuli.script.Screen;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import utility.AllMyUtilities;


public class RunTheBot extends AllMyUtilities{
	//public static WebDriver driver;
	String baseURL = "Http://automationpractice.Com/";
	Screen screen = new Screen();
	
	
@BeforeTest
public void SetUp() throws InterruptedException, FindFailed {
	
	setUp();
	Thread.sleep(5000);
	
}
		
  @Test
  public void TestTheApp() throws InterruptedException, FindFailed {
	  
	  //Login
	  driver.get(baseURL);
		System.out.println("Title of Test Page is: "+driver.getTitle());  
		Thread.sleep(2000);
	   Pattern search = new Pattern(System.getProperty("user.dir")+"//DesignDocs//AppDesign//search.PNG");
	   Pattern lenseicon = new Pattern(System.getProperty("user.dir")+"//DesignDocs//AppDesign//LenseIcon.PNG");
	   Pattern chiffonDress = new Pattern(System.getProperty("user.dir")+"//DesignDocs//AppDesign//chiffonDress.PNG");
	   Pattern addToCart = new Pattern(System.getProperty("user.dir")+"//DesignDocs//AppDesign//addToCart.PNG");
	   Pattern ProceedToChkOut = new Pattern(System.getProperty("user.dir")+"//DesignDocs//AppDesign//ProceedToChkOut.PNG");
	   Pattern ProceedToChkOut_2 = new Pattern(System.getProperty("user.dir")+"//DesignDocs//AppDesign//ProceedToChkOut_2.PNG");
	   
	   
	   screen.type(search, "Printed Dress");
	   screen.click(lenseicon);
	   Thread.sleep(2000);
	   screen.click(chiffonDress);
	   
	   pageScroll();
	   
	   screen.click(addToCart);
	   screen.click(ProceedToChkOut);
	   Thread.sleep(2000);
	   
	   pageScroll();
	   screen.click(ProceedToChkOut_2);
	  
  }
  
  @AfterTest
  public void TearDown() throws FindFailed, InterruptedException {
	  
	  driver.close();
	  Thread.sleep(2000);
	  KatalonOperation();
	  saveTheScript(System.getProperty("user.dir")+"\\src\\autoGeneratedScripts");
	  
	//  driver.quit();
	  System.out.println("Hurraaaaay-----The Test have been PASSED");
  }
  
}
